# Generated by Django 4.2.15 on 2025-11-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_symptomsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('symptoms', models.CharField(max_length=200)),
                ('suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthIssue',
        ),
        migrations.DeleteModel(
            name='SymptomSuggestion',
        ),
    ]
