# Generated by Django 4.2.15 on 2025-11-05 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudapp', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
